// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthCode = `-- name: ConsumeAuthCode :exec
UPDATE auth_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeAuthCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeAuthCode, id)
	return err
}

const createAuthCode = `-- name: CreateAuthCode :exec
INSERT INTO auth_codes (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateAuthCodeParams struct {
	UserID    uuid.UUID
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createAuthCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	return err
}

const getLatestActiveAuthCode = `-- name: GetLatestActiveAuthCode :one
SELECT id, code_hash, attempts, created_at
FROM auth_codes
WHERE user_id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestActiveAuthCodeRow struct {
	ID        uuid.UUID
	CodeHash  string
	Attempts  int32
	CreatedAt pgtype.Timestamptz
}

// Newest unspent, unexpired code for a user. Verification matches against this
// one row so old codes cannot be reused once a newer one is requested.
func (q *Queries) GetLatestActiveAuthCode(ctx context.Context, userID uuid.UUID) (GetLatestActiveAuthCodeRow, error) {
	row := q.db.QueryRow(ctx, getLatestActiveAuthCode, userID)
	var i GetLatestActiveAuthCodeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const incrementAuthCodeAttempts = `-- name: IncrementAuthCodeAttempts :exec
UPDATE auth_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementAuthCodeAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementAuthCodeAttempts, id)
	return err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email
`

type UpsertUserByEmailRow struct {
	ID    uuid.UUID
	Email string
}

// Requesting a code for an unknown email transparently creates the account, so
// there is no separate sign-up step. The no-op ON CONFLICT update lets us return
// the existing row's id when the account already exists.
func (q *Queries) UpsertUserByEmail(ctx context.Context, email string) (UpsertUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, email)
	var i UpsertUserByEmailRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}
