// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlements.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEntitlement = `-- name: GetEntitlement :one
SELECT plan, until FROM entitlements WHERE user_id = $1
`

type GetEntitlementRow struct {
	Plan  string
	Until pgtype.Timestamptz
}

// The user's current suite-wide entitlement. A user with no row is on the free
// plan (the default for every new account); callers translate ErrNoRows to free.
func (q *Queries) GetEntitlement(ctx context.Context, userID uuid.UUID) (GetEntitlementRow, error) {
	row := q.db.QueryRow(ctx, getEntitlement, userID)
	var i GetEntitlementRow
	err := row.Scan(&i.Plan, &i.Until)
	return i, err
}

const upsertEntitlement = `-- name: UpsertEntitlement :exec
INSERT INTO entitlements (user_id, plan, status, until, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
  SET plan = EXCLUDED.plan, status = EXCLUDED.status, until = EXCLUDED.until, updated_at = now()
`

type UpsertEntitlementParams struct {
	UserID uuid.UUID
	Plan   string
	Status string
	Until  pgtype.Timestamptz
}

// Sets a user's suite-wide entitlement. Called from the billing webhook (and the
// dev grant) so a single payment flips the one entitlement that every app reads.
// status mirrors the Stripe subscription status for auditing.
func (q *Queries) UpsertEntitlement(ctx context.Context, arg UpsertEntitlementParams) error {
	_, err := q.db.Exec(ctx, upsertEntitlement,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.Until,
	)
	return err
}
