// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthCode struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CodeHash   string
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	Attempts   int32
	CreatedAt  pgtype.Timestamptz
}

type Entitlement struct {
	UserID           uuid.UUID
	Plan             string
	Status           string
	Until            pgtype.Timestamptz
	StripeCustomerID pgtype.Text
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}
