/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a login code
         * @description Emails a 6-digit login code, creating the account if the address is new. Always returns a generic acknowledgement so it cannot reveal whether an account exists. Within the resend cooldown it acknowledges without sending a new code, leaving the still-valid one in place.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email to send the login code to */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.AuthRequestCodeInput"];
                };
            };
            responses: {
                /** @description Deliberately vague acknowledgement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.MessageResponse"];
                    };
                };
                /** @description Invalid email */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a login code
         * @description Exchanges an email + 6-digit code for a session token. The token carries the account's current suite-wide entitlement, so every app learns paid access from the token alone.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email and the code that was emailed */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.AuthVerifyCodeInput"];
                };
            };
            responses: {
                /** @description The session token plus the account it belongs to */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.VerifyResponse"];
                    };
                };
                /** @description Malformed body or invalid email */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.ErrorResponse"];
                    };
                };
                /** @description Invalid or expired code */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.AuthRequestCodeInput": {
            email: string;
        };
        "api.AuthVerifyCodeInput": {
            code: string;
            email: string;
        };
        "api.ErrorResponse": {
            error: string;
        };
        "api.MessageResponse": {
            message: string;
        };
        "api.User": {
            email: string;
            id: string;
        };
        "api.VerifyResponse": {
            token: string;
            user: components["schemas"]["api.User"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
